[credentials.usernames.tobi]
email = "tobi@tennis.cz"
name = "Tobi"
password = "$2b$12$JFIUfFNqku4ryT0xf71DY.hO6GU/RgFA0HNslmeAJ/KK9ucW56uoG"

[credentials.usernames.kuba]
email = "kuba@tennis.cz"
name = "Kuba"
password = "$2b$12$lJX2ij3ZYMQykvV1HQT1eeTxKDDRlE2ug3AYRKBpDXwldIxY1PTAK"

[credentials.usernames.jirka]
email = "jirka@tennis.cz"
name = "Jirka"
password = "$2b$12$5CJAe3FRhhhez8fHWXqr1Oqi1qbv/rxqNFPl2s.EMyzj3qikn6fX6"

[cookie]
name = "tennis_elo_cookie"
key = "super_tajny_klic_pro_podpis_123"
expiry_days = 30