[credentials]
usernames = {
    tobi = { email = "tobi@tenis.cz", name = "Tobi", password = "$2b$12$UyPB40i.0ILPs0i0pE5eSuprNKi8JugFeytcInL.KkSZOj7jY4iuK" },
    kuba = { email = "kuba@tenis.cz", name = "Kuba", password = "$2b$12$gtN1E0mfQhhuD/dWwlLvC.n/n4wlmq8j0nWL40s.zkMUW8.07x7Uq" },
    jirka = { email = "jirka@tenis.cz", name = "Jirka", password = "$2b$12$Sl1FvmUzYKbYGJz13BF9k.ASkZ7Y4dai2KrgY.GQFpdNlDPBlBQa6" },
    kavic = { email = "kavic@tenis.cz", name = "Kávič", password = "$2b$12$yJo9roc03R1/qyuu0QQZ1e7hO.9Co1RjehuXqJTReIGGQEsCc0j/G" },
    risa = { email = "risa@tenis.cz", name = "Ríša", password = "$2b$12$UHk6j0cAwLgCAYK/jIf55OMOe3v9s2dS/ev9taVkSymzcrvD5cpA6" },
}

[cookie]
expiry_days = 30
key = "tajny_klic_123"
name = "tennis_elo_auth"
